name: Release

on:
  push:
    branches: [ main ]
    tags-ignore:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
        
    - name: Restore dependencies
      run: dotnet restore src/Jedi.sln
      
    - name: Build
      run: dotnet build src/Jedi.sln --configuration Release --no-restore
      
    - name: Test
      run: dotnet test src/Jedi.sln --configuration Release --no-build --verbosity normal --logger trx
        
    - name: Zip
      uses: montudor/action-zip@v1.0.0
      with:
        args: zip -qq -r Jedi.zip target

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create a release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
        artifacts: "Jedi.zip,LICENSE"
