name: Release

on:
  push:
    paths:
      - "src/**"
    branches: [ main ]

jobs:
  release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.0.0-alpha2
      with:
        branch: HEAD
        major_pattern: (MAJOR)
        minor_pattern: (MINOR)
        version_format: ${major}.${minor}.${patch}
        bump_each_commit: false
        search_commit_body: false
        user_format_type: json
